from __future__ import annotations

import argparse
import json
import shutil
from pathlib import Path


def _read_json(path: Path) -> dict[str, object] | list[object]:
    return json.loads(path.read_text(encoding="utf-8"))


def _rows_for_study(study_manifest: dict[str, object], name: str) -> int:
    studies = study_manifest.get("studies", {})
    if not isinstance(studies, dict):
        return 0
    payload = studies.get(name, {})
    if not isinstance(payload, dict):
        return 0
    return int(payload.get("rows", 0) or 0)


def _write_export_readme(out_root: Path) -> None:
    study_manifest = _read_json(out_root / "study_manifest.json") if (out_root / "study_manifest.json").exists() else {}
    plots_manifest = _read_json(out_root / "plots_manifest.json") if (out_root / "plots_manifest.json").exists() else {}
    tables_manifest = _read_json(out_root / "tables_manifest.json") if (out_root / "tables_manifest.json").exists() else {}

    plot_names = plots_manifest.get("plots", []) if isinstance(plots_manifest, dict) else []
    table_map = tables_manifest.get("tables", {}) if isinstance(tables_manifest, dict) else {}
    main_plots = [
        "init_recall_vs_m_facets",
        "main_recall_vs_avg_computations_facets",
        "main_qps_vs_index_overhead_facets",
        "main_recall_vs_qps_facets",
        "main_training_time_bars",
    ]
    ram_plots = [
        "main_serving_ram_vs_index_overhead_facets",
        "appendix_query_ram_vs_index_overhead_facets",
        "appendix_query_ram_bars",
        "appendix_serving_ram_vs_index_overhead_facets",
        "appendix_serving_ram_bars",
    ]
    appendix_plots = [
        "main_load_balance_bucket_rank_facets",
        "appendix_computation_range_bars",
        "appendix_qps_bars",
        "appendix_serving_footprint_bars",
        "appendix_ablation_qps_bars",
        "appendix_ablation_training_time_bars",
    ]

    text = f"""# Paper Exports

Canonical generated export bundle for the finished AdaptIVF paper run.

This directory is designed to be publishable: it contains the normalized study summaries, paper-ready plots, table CSVs, serving-RAM measurements, and a lightweight appendix scaffold. The directory is regenerated by the main pipeline rather than maintained manually.

## What Is Here

- `initialization/`, `competitiveness/`, `ablations/`: normalized per-study CSV/JSON summaries
- `tables/`: compact CSV tables used by the paper
- top-level `*.pdf` / `*.png` / `*.csv`: paper and appendix plots with their plot-source CSVs
- `serving_ram.json` and `serving_ram.csv`: isolated subprocess serving-RSS measurements for the canonical competitiveness experiments
- `run_plan.json`, `study_manifest.json`, `plots_manifest.json`, `tables_manifest.json`: machine-readable manifests for the generated bundle
- `appendix.tex`: a copyable supplementary-material scaffold

All manifests and artifact-provenance paths in this bundle are stored as
repo-relative paths rather than machine-local absolute paths.

Study row counts in this finished bundle:

- initialization: {_rows_for_study(study_manifest, "initialization")} rows
- competitiveness: {_rows_for_study(study_manifest, "competitiveness")} rows
- ablations: {_rows_for_study(study_manifest, "ablations")} rows

## Reproduce This Directory

From the repository root:

```bash
bash scripts/download_datasets.sh
bash scripts/run_paper.sh
```

If the experiment artifacts already exist and only the export directory needs to be rebuilt:

```bash
PYTHONPATH=src python -m collect --out-root paper_exports --experiments-root ../experiments/adaptivf --data-root ../data
PYTHONPATH=src python -m tables --out-root paper_exports
PYTHONPATH=src python -m plots --out-root paper_exports
PYTHONPATH=src python -m export_bundle --out-root paper_exports
```

The root repository README gives the high-level workflow; see `scripts/README.md` for the runnable command surface.

## Main Figures

{chr(10).join(f"- `{name}.pdf`" for name in main_plots if name in plot_names)}

## Appendix / Systems Figures

{chr(10).join(f"- `{name}.pdf`" for name in appendix_plots if name in plot_names)}

## RAM Figures

{chr(10).join(f"- `{name}.pdf`" for name in ram_plots if name in plot_names)}

## Tables

{chr(10).join(f"- `{Path(path).name}`" for path in table_map.values())}

## Notes

- All results are CPU-only and were generated without GPU acceleration.
- `index_overhead_mb` is the primary compactness metric.
- `avg_computations` is the canonical workload metric.
- `query_mem_delta_mb` reports isolated subprocess query-path RSS deltas.
- `rss_serving_mb` reports isolated subprocess serving RSS after loading the artifacts required for query serving.
- The exported RAM figures intentionally separate query-path RSS deltas from post-load serving RSS.
"""
    (out_root / "README.md").write_text(text, encoding="utf-8")


def _copy_appendix_template(out_root: Path) -> None:
    repo_root = Path(__file__).resolve().parents[1]
    template = repo_root / "docs" / "paper_exports_appendix_template.tex"
    if template.exists():
        shutil.copyfile(template, out_root / "appendix.tex")


def main() -> None:
    parser = argparse.ArgumentParser(description="Write non-result export-bundle docs for paper_exports.")
    parser.add_argument("--out-root", default="paper_exports")
    args = parser.parse_args()

    out_root = Path(args.out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    _write_export_readme(out_root)
    _copy_appendix_template(out_root)
    print(out_root / "README.md")


if __name__ == "__main__":
    main()
